################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_buffer_full_notify.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_disable.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_enable.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_event_filter.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_event_unfilter.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_initialize.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_interrupt_control.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_isr_enter_insert.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_isr_exit_insert.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_object_register.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_object_unregister.c \
C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_user_event_insert.c 

OBJS += \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_buffer_full_notify.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_disable.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_enable.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_filter.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_unfilter.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_initialize.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_interrupt_control.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_enter_insert.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_exit_insert.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_register.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_unregister.o \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_user_event_insert.o 

C_DEPS += \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_buffer_full_notify.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_disable.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_enable.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_filter.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_unfilter.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_initialize.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_interrupt_control.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_enter_insert.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_exit_insert.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_register.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_unregister.d \
./Middlewares/ThreadX/RTOS/TraceX/tx_trace_user_event_insert.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/ThreadX/RTOS/TraceX/tx_trace_buffer_full_notify.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_buffer_full_notify.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_disable.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_disable.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_enable.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_enable.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_filter.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_event_filter.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_unfilter.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_event_unfilter.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_initialize.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_initialize.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_interrupt_control.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_interrupt_control.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_enter_insert.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_isr_enter_insert.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_exit_insert.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_isr_exit_insert.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_register.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_object_register.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_unregister.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_object_unregister.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/ThreadX/RTOS/TraceX/tx_trace_user_event_insert.o: C:/Users/manojkumar.ch/STM32CubeIDE/Project/Tx_MPU/Middlewares/ST/threadx/common/src/tx_trace_user_event_insert.c Middlewares/ThreadX/RTOS/TraceX/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DTX_INCLUDE_USER_DEFINE_FILE -DUSE_HAL_DRIVER -DSTM32H747xx -c -I../../../Core/Inc -I../../../Common/Inc -I../../../Middlewares/ST/threadx/common/inc/ -I../../../Middlewares/ST/threadx/common_modules/inc/ -I../../../Middlewares/ST/threadx/common_modules/module_manager/inc/ -I../../../Middlewares/ST/threadx/ports_module/cortex_m7/gnu/inc/ -I../../../Drivers/BSP/STM32H747I-DISCO -I../../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../../Drivers/CMSIS/Include -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-ThreadX-2f-RTOS-2f-TraceX

clean-Middlewares-2f-ThreadX-2f-RTOS-2f-TraceX:
	-$(RM) ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_buffer_full_notify.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_buffer_full_notify.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_buffer_full_notify.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_disable.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_disable.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_disable.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_enable.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_enable.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_enable.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_filter.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_filter.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_filter.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_unfilter.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_unfilter.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_event_unfilter.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_initialize.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_initialize.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_initialize.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_interrupt_control.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_interrupt_control.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_interrupt_control.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_enter_insert.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_enter_insert.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_enter_insert.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_exit_insert.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_exit_insert.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_isr_exit_insert.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_register.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_register.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_register.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_unregister.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_unregister.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_object_unregister.su ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_user_event_insert.d ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_user_event_insert.o ./Middlewares/ThreadX/RTOS/TraceX/tx_trace_user_event_insert.su

.PHONY: clean-Middlewares-2f-ThreadX-2f-RTOS-2f-TraceX

